version: "2"
services:
  nginx:
    image: nginx:1.9
    volumes:
      - ./volumes/nginx/tdiary.conf:/etc/nginx/conf.d/tdiary.conf:ro

  tdiary:
    image: minimum2scp/magellan-tdiary:0.1.12
    command: >
      bundle exec passenger start -e production -p 80 --max-pool-size 3
      --pid-file tmp/passenger.pid --load-shell-envvars --static-files-dir public
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=tdiary
      - MYSQL_PASSWORD=tdiary
      - MYSQL_DATABASE=tdiary
      #- TDIARY_BASIC_AUTH_USERNAME=tdiary
      #- TDIARY_BASIC_AUTH_PASSWORD=tdiary
      - TDIARY_CSRF_PROTECTION_KEY=FAKE_LOCALTEST_KEY
      - NEW_RELIC_LICENSE_KEY=DUMMY_LICENSE_KEY
      - NEW_RELIC_APP_NAME=magellan-tdiary-local-dev
      #- RACK_MINI_PROFILE_ENABLED=false
      #- RUBY_GC_PROFILER_ENABLED=false

  db:
    image: mysql:5.6
    volumes:
      - ./volumes/mysql/charset.cnf:/etc/mysql/conf.d/charset.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=tdiary
      - MYSQL_PASSWORD=tdiary
      - MYSQL_DATABASE=tdiary

